steps:
  - name: ":elixir: :umbrella: Tests"
    command: "mix test"
    plugins:
      docker-compose#v1.8.3:
        run: app

  - name: ":credo: Credo"
    command: "mix credo --strict"
    plugins:
      docker-compose#v1.8.3:
        run: app
